version: "3"
services:
  object-detection-react:
    build: ./
    volumes:
      - ./package.json:/var/www/package.json
      - ./package-lock.json:/var/www/package-lock.json
      - ./public:/var/www/public/
      - ./src:/var/www/src/
    expose:
     - "3000"
  object-detection-nginx:
    build: ./nginx
    ports:
     - 80:80
     - 443:443
    depends_on:
     - object-detection-react