---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-react
spec:
  replicas: 3
  selector:
    matchLabels:
      app: object-detection-react-deployment
  template:
    metadata:
      labels:
        app: object-detection-react-deployment
        version: v1
    spec:
      containers:
        - name: objection-detection-react
          image: wakabaunoibm/object-detection-react:v0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          # add below
          env:
            - name: HOST_IP
              value: <PUBLIC_IP>
            - name: SCHEME
              value: http

---
apiVersion: v1
kind: Service
metadata:
  name: object-detection-react-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32001
      name: http
  type: NodePort
  selector:
    app: object-detection-react-deployment